//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeRidderJoris_GRPLTId1._1_DM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameModeRank
    {
        public int gameModeRankId { get; set; }
        public int rankId { get; set; }
        public int gameModeId { get; set; }
    
        public virtual GameMode GameMode { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
