//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeRidderJoris_GRPLTId1._1_DM_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToernooiDBEntities : DbContext
    {
        public ToernooiDBEntities()
            : base("name=ToernooiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prijs> Prijs { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Speler> Speler { get; set; }
        public virtual DbSet<Toernooi> Toernooi { get; set; }
    }
}
