//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeRidderJoris_GRPLTId1._1_DM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijs
    {
        public int prijsId { get; set; }
        public int toernooiId { get; set; }
        public string prijsnaam { get; set; }
        public int spelerId { get; set; }
    
        public virtual Toernooi Toernooien { get; set; }
        public virtual Speler Spelers { get; set; }
    }
}
