//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeRidderJoris_GRPLTId1._1_DM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speler
    {
        public int spelerId { get; set; }
        public string voorNaam { get; set; }
        public string achterNaam { get; set; }
        public string nickNaam { get; set; }
        public string wachtWoord { get; set; }
        public string email { get; set; }
        public System.DateTime geboorteDatum { get; set; }
        public string geboortePlaats { get; set; }
    
        public virtual Prijs Prijs { get; set; }
    }
}
