//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeRidderJoris_GRPLTId1._1_DM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speler
    {
        public int spelerID { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Nicknaam { get; set; }
        public string Wachtwoord { get; set; }
        public string Email { get; set; }
        public System.DateTime Geboortedatum { get; set; }
        public string Geboorteplaats { get; set; }
    
        public virtual Prijs Prijs { get; set; }
    }
}
